version: '3'

services:
  postgres:
    image: postgres
    container_name: fsw-barber-db
    environment:
      POSTGRES_DB: fsw-barber-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5433:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
